alias ls="ls -alhG"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias eb="vim ~/.bash_aliases"
alias rb="source ~/.bash_aliases"
alias check_start="vim /var/log/cloud-init-output.log"
alias c='clear'
